### ISSUE TITLE
[Vulnerability] Password can be bypassed on locked screen with Ctrl+Alt+F7

### ISSUE THREAD

**Issue by NovaAndrom3da** [JezerM/web-greeter-themes#3]
Light locker can be bypassed by switching to the open TTY of the session. A workaround could be for the user to change the default graphical TTY for X11 to one greater or equal to 13 (More than the number of default function keys)

**Comment by JezerM** [comment]
Thanks, but this is not related to web-greeter/nody-greeter/sea-greeter but to light-locker. Setting the default graphical TTY for X11 should be the user task or light-locker task.

Also, it is supposed that light-locker changes back to the locked TTY even if you change to TTY-7 with `Ctrl+Alt+F7`. If it's not doing it, then you should report it to light-locker issues.

**Comment by NovaAndrom3da** [comment]
Oh, okay, thanks. I thought it might have had something to do with web-greeter (btw, why did I end up putting the issue in this repo instead of the main web-greeter repo? Guess I was tired, lol 🤔).
